import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // ─────────────────────────────────────────────
  // AUTH & USER MANAGEMENT
  // ─────────────────────────────────────────────

  users: defineTable({
    // From Clerk JWT — use tokenIdentifier as the stable key
    tokenIdentifier: v.string(),
    clerkId: v.string(),
    name: v.string(),
    email: v.string(),
    role: v.union(
      v.literal("admin"),
      v.literal("trainer"),
      v.literal("client")
    ),
    // For clients — which trainer they belong to (userId of trainer)
    trainerId: v.optional(v.id("users")),
    createdAt: v.number(),
  })
    .index("by_token", ["tokenIdentifier"])
    .index("by_clerk_id", ["clerkId"])
    .index("by_trainer", ["trainerId"])
    .index("by_role", ["role"]),

  // Invite codes generated by trainers to onboard clients
  inviteCodes: defineTable({
    code: v.string(),           // short random code e.g. "ABC123"
    trainerId: v.id("users"),   // the trainer who generated it
    usedBy: v.optional(v.id("users")), // null until claimed
    usedAt: v.optional(v.number()),
    expiresAt: v.number(),      // timestamp
    createdAt: v.number(),
  })
    .index("by_code", ["code"])
    .index("by_trainer", ["trainerId"]),

  // ─────────────────────────────────────────────
  // FITNESS DATA (unchanged structure, now user-scoped)
  // ─────────────────────────────────────────────

  workouts: defineTable({
    userId: v.id("users"),
    date: v.string(),
    notes: v.optional(v.string()),
    time: v.optional(v.string()),
    duration: v.optional(v.number()),
    exercises: v.array(
      v.object({
        exercise_name: v.string(),
        sets: v.number(),
        reps: v.number(),
        weight: v.number(),
      })
    ),
  }).index("by_user", ["userId"]),

  cardioLogs: defineTable({
    userId: v.id("users"),
    date: v.string(),
    type: v.string(),
    distance: v.optional(v.number()),
    duration: v.optional(v.number()),
    notes: v.optional(v.string()),
    time: v.optional(v.string()),
  }).index("by_user", ["userId"]),

  bodyMetrics: defineTable({
    userId: v.id("users"),
    date: v.string(),
    weight: v.optional(v.number()),
    height: v.optional(v.number()),
    body_fat_perc: v.optional(v.number()),
    chest: v.optional(v.number()),
    waist: v.optional(v.number()),
    hips: v.optional(v.number()),
    bicep: v.optional(v.number()),
    thigh: v.optional(v.number()),
  }).index("by_user", ["userId"]),

  nutritionLogs: defineTable({
    userId: v.id("users"),
    date: v.string(),
    calories: v.optional(v.number()),
    protein: v.optional(v.number()),
    carbs: v.optional(v.number()),
    fat: v.optional(v.number()),
  }).index("by_user", ["userId"]),

  // Progress photos — NOT accessible to trainers
  progressPhotos: defineTable({
    userId: v.id("users"),
    date: v.string(),
    photo_url: v.string(),
    notes: v.optional(v.string()),
  }).index("by_user", ["userId"]),

  // ─────────────────────────────────────────────
  // AI CHAT
  // ─────────────────────────────────────────────

  conversations: defineTable({
    userId: v.id("users"),
    created_at: v.number(),
    updated_at: v.number(),
  }).index("by_user", ["userId"]),

  messages: defineTable({
    conversationId: v.id("conversations"),
    role: v.union(
      v.literal("user"),
      v.literal("assistant"),
      v.literal("system")
    ),
    content: v.string(),
    sources: v.optional(v.array(v.string())),
    created_at: v.number(),
  }).index("by_conversation_and_time", ["conversationId", "created_at"]),

  bookKnowledge: defineTable({
    book_title: v.string(),
    chunk_index: v.number(),
    content: v.string(),
    embedding: v.array(v.float64()),
  }).vectorIndex("by_embedding", {
    vectorField: "embedding",
    dimensions: 384,
  }),

  // Audit logs for sensitive actions
  auditLogs: defineTable({
    actorId: v.id("users"),
    action: v.string(),
    targetId: v.optional(v.string()),
    metadata: v.optional(v.any()),
    timestamp: v.number(),
  }).index("by_timestamp", ["timestamp"]),
});
